dbt_deployment:
  outputs:
    dev:
      catalog: dbt_core
      host: "{{ env_var('DATABRICKS_HOST') }}.azuredatabricks.net"
      http_path: "/sql/1.0/warehouses/{{ env_var('DATABRICKS_SQL') }}"
      schema: dev
      threads: 1
      auth_type: oauth
      client_id: "{{ env_var('DATABRICKS_CLIENT_ID') }}" 
      client_secret: "{{ env_var('DATABRICKS_CLIENT_SECRET') }}" 
      type: databricks
  target: dev
